version: '3.8'

services:
  msr-lean:
    image: azdevopssttlabacr.azurecr.io/msr-1011-lean-original-recipe:Fixes_22-11-22
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./application.properties:/tmp/application.properties
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - ./application.properties:/tmp/application.properties